"""
A fake Ollama server, used ONLY to test that LLMClient's request/response
handling logic is correct. This is not part of the actual product -
delete this file once you've verified things work, or keep it in
tests/ as a way to run agent tests without needing Ollama installed.
"""
import json
from http.server import BaseHTTPRequestHandler, HTTPServer


class FakeOllamaHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        length = int(self.headers["Content-Length"])
        body = json.loads(self.rfile.read(length))

        if body.get("format") == "json":
            fake_reply = json.dumps({"type": "Invoice", "confidence": 0.93})
        else:
            fake_reply = "This is a fake answer generated by the mock Ollama server."

        response = {"response": fake_reply, "model": body.get("model"), "done": True}

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps(response).encode())

    def log_message(self, format, *args):
        pass  # silence default request logging


def run_server(port=11434):
    server = HTTPServer(("localhost", port), FakeOllamaHandler)
    server.serve_forever()


if __name__ == "__main__":
    run_server()
